{
 "title": "FreeTon node Alerts",
 "tags": [
  "prod",
  "alerts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Node DIff",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_diff{instance=\"_NODE-IP_:8080\"}",
     "legendFormat": "NodeDiff"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_balance{instance=\"_NODE-IP_:8080\"}",
     "legendFormat": "WalletBalance"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"_NODE-IP_:8080\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"_NODE-IP_:8080\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"_NODE-IP_:8080\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=\"_NODE-IP_:8080\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100* (node_memory_MemTotal_bytes{instance=\"_NODE-IP_:8080\"} - node_memory_MemAvailable_bytes{instance=\"_NODE-IP_:8080\"}) / node_memory_MemTotal_bytes{instance=\"_NODE-IP_:8080\"}",
     "legendFormat": "Memory_Avaliable"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=\"_NODE-IP_:8080\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=\"_NODE-IP_:8080\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Input Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"_NODE-IP_:8080\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_receive"
    }
   ]
  },
  {
   "title": "Ouptut Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"_NODE-IP_:8080\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  }
 ]
}